---
kind: pipeline
name: python-2

steps:
- name: test
  image: python:2
  commands:
  - pip install -r requirements.txt
  - pytest
---
kind: pipeline
name: python-3

steps:
- name: test
  image: python:3
  commands:
  - pip install -r requirements.txt
  - pytest
